import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';

import '@/styles/reset.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SangHo | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100vh]`}>
        <div className="sticky z-50 top-0">
          <Header />
        </div>
        <div className="mx-auto w-[90%]">{children}</div>
        <div className="sticky z-50 bottom-0">
          <Footer />
        </div>
      </body>
    </html>
  );
}
